manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: caksoylar
      url-base: https://github.com/caksoylar
    - name: xudongz
      url-base: https://github.com/xudongzheng
    - name: urob
      url-base: https://github.com/urob
    - name: zephyr35
      url-base: https://github.com/petejohanson
  projects:
    - name: zmk
      remote: zephyr35 #zmkfirmware
      revision: core/zephyr-3.5-update  #main
      import: app/west.yml
    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: main
  self:
    path: config